-- MySQL Script generated by MySQL Workbench
-- Thu Jun 26 04:43:17 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema tap_informatica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tap_informatica` ;
CREATE SCHEMA IF NOT EXISTS `tap_informatica` DEFAULT CHARACTER SET latin1 ;
USE `tap_informatica` ;

-- -----------------------------------------------------
-- Table `tap_informatica`.`Caracteristica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Caracteristica` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Caracteristica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `editable` TINYINT(1) NOT NULL DEFAULT 0,
  `adjuntable` TINYINT(1) NOT NULL DEFAULT 0,
  `multiplicidad` INT NOT NULL DEFAULT 1,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`LineaInvestigacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`LineaInvestigacion` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`LineaInvestigacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Area` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Area` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `LineaInvestigacion_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `LineaInvestigacion_id`),
  INDEX `fk_Area_LineaInvestigacion1_idx` (`LineaInvestigacion_id` ASC),
  CONSTRAINT `fk_Area_LineaInvestigacion1`
    FOREIGN KEY (`LineaInvestigacion_id`)
    REFERENCES `tap_informatica`.`LineaInvestigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`LapsoAcademico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`LapsoAcademico` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`LapsoAcademico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fechaInicio` TIMESTAMP NOT NULL,
  `fechaFin` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`TAP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`TAP` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`TAP` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Area_id` INT NOT NULL,
  `LineaInvestigacion_id` INT NOT NULL,
  `fechaCreacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaInicio` TIMESTAMP NULL DEFAULT NULL,
  `fechaFin` TIMESTAMP NULL DEFAULT NULL,
  `fechaAprobacion` TIMESTAMP NULL DEFAULT NULL,
  `lapsoInicio` INT NOT NULL,
  `lapsoFin` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TAP_Area1_idx` (`Area_id` ASC, `LineaInvestigacion_id` ASC),
  INDEX `fk_TAP_LapsoAcademico1_idx` (`lapsoInicio` ASC),
  INDEX `fk_TAP_LapsoAcademico2_idx` (`lapsoFin` ASC),
  CONSTRAINT `fk_TAP_Area1`
    FOREIGN KEY (`Area_id` , `LineaInvestigacion_id`)
    REFERENCES `tap_informatica`.`Area` (`id` , `LineaInvestigacion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAP_LapsoAcademico1`
    FOREIGN KEY (`lapsoInicio`)
    REFERENCES `tap_informatica`.`LapsoAcademico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TAP_LapsoAcademico2`
    FOREIGN KEY (`lapsoFin`)
    REFERENCES `tap_informatica`.`LapsoAcademico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`tap_ica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`tap_ica` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`tap_ica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `Caracteristica_id` INT NOT NULL,
  `TAP_id` INT NOT NULL,
  `versionPrevia` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_tap_ica_Caracteristica1_idx` (`Caracteristica_id` ASC),
  INDEX `fk_tap_ica_TAP1_idx` (`TAP_id` ASC),
  INDEX `fk_tap_ica_tap_ica1_idx` (`versionPrevia` ASC),
  CONSTRAINT `fk_tap_ica_Caracteristica1`
    FOREIGN KEY (`Caracteristica_id`)
    REFERENCES `tap_informatica`.`Caracteristica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tap_ica_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tap_ica_tap_ica1`
    FOREIGN KEY (`versionPrevia`)
    REFERENCES `tap_informatica`.`tap_ica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Archivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Archivo` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Archivo` (
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `adjunto` BLOB NOT NULL,
  `tap_ica_id` INT NOT NULL,
  PRIMARY KEY (`tap_ica_id`),
  CONSTRAINT `fk_Archivo_tap_ica1`
    FOREIGN KEY (`tap_ica_id`)
    REFERENCES `tap_informatica`.`tap_ica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Estado` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Ciudad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `Estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Ciudad_Estado1_idx` (`Estado_id` ASC),
  CONSTRAINT `fk_Ciudad_Estado1`
    FOREIGN KEY (`Estado_id`)
    REFERENCES `tap_informatica`.`Estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Municipio` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Municipio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `Ciudad_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Municipio_Ciudad1_idx` (`Ciudad_id` ASC),
  CONSTRAINT `fk_Municipio_Ciudad1`
    FOREIGN KEY (`Ciudad_id`)
    REFERENCES `tap_informatica`.`Ciudad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Empresa` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `RIF` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `correoElectronico` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `RIF_UNIQUE` (`RIF` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Direccion` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `telefono` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `otroContacto` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `Municipio_id` INT NOT NULL,
  `Empresa_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_Direccion_Municipio1_idx` (`Municipio_id` ASC),
  INDEX `fk_Direccion_Empresa1_idx` (`Empresa_id` ASC),
  CONSTRAINT `fk_Direccion_Municipio1`
    FOREIGN KEY (`Municipio_id`)
    REFERENCES `tap_informatica`.`Municipio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Direccion_Empresa1`
    FOREIGN KEY (`Empresa_id`)
    REFERENCES `tap_informatica`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`EstadoRevision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`EstadoRevision` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`EstadoRevision` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `Icono` BLOB NOT NULL,
  `fecha` VARCHAR(45) NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Estatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Estatus` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Estatus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `cedulaIdentidad` VARCHAR(45) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cedulaIdentidad_UNIQUE` (`cedulaIdentidad` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`ROL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`ROL` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`ROL` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` VARCHAR(200) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`rol_uio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`rol_uio` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`rol_uio` (
  `Usuario_id` INT NOT NULL,
  `ROL_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Usuario_id`, `ROL_id`),
  INDEX `fk_rol_uio_Usuario1_idx` (`Usuario_id` ASC),
  INDEX `fk_rol_uio_ROL1_idx` (`ROL_id` ASC),
  CONSTRAINT `fk_rol_uio_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `tap_informatica`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rol_uio_ROL1`
    FOREIGN KEY (`ROL_id`)
    REFERENCES `tap_informatica`.`ROL` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Evaluador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Evaluador` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Evaluador` (
  `TAP_id` INT NOT NULL,
  `Usuario_id` INT NOT NULL,
  `ROL_id` INT NOT NULL,
  `nota` INT NULL DEFAULT NULL,
  `retirado` TINYINT(1) NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAP_id`, `Usuario_id`, `ROL_id`),
  INDEX `fk_Evaluador_TAP1_idx` (`TAP_id` ASC),
  INDEX `fk_Evaluador_rol_uio1_idx` (`Usuario_id` ASC, `ROL_id` ASC),
  CONSTRAINT `fk_Evaluador_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluador_rol_uio1`
    FOREIGN KEY (`Usuario_id` , `ROL_id`)
    REFERENCES `tap_informatica`.`rol_uio` (`Usuario_id` , `ROL_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Inscripcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Inscripcion` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Inscripcion` (
  `TAP_id` INT NOT NULL,
  `Usuario_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAP_id`),
  INDEX `fk_Inscripcion_Usuario1_idx` (`Usuario_id` ASC),
  CONSTRAINT `fk_Inscripcion_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Inscripcion_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `tap_informatica`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`TutorExterno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`TutorExterno` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`TutorExterno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellido` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cedulaIdentidad` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `telefono` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `correoElectronico` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `curriculum` BLOB NOT NULL,
  `Direccion_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`, `Direccion_id`),
  INDEX `fk_TutorExterno_Direccion1_idx` (`Direccion_id` ASC),
  UNIQUE INDEX `cedulaIdentidad_UNIQUE` (`cedulaIdentidad` ASC),
  CONSTRAINT `fk_TutorExterno_Direccion1`
    FOREIGN KEY (`Direccion_id`)
    REFERENCES `tap_informatica`.`Direccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Pasantia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Pasantia` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Pasantia` (
  `notaExterna` INT NULL DEFAULT NULL,
  `TAP_id` INT NOT NULL,
  `TutorExterno_Id` INT NOT NULL,
  `Direccion_id` INT NOT NULL,
  PRIMARY KEY (`TAP_id`),
  INDEX `fk_Pasantia_TutorExterno1_idx` (`TutorExterno_Id` ASC, `Direccion_id` ASC),
  CONSTRAINT `fk_Pasantia_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pasantia_TutorExterno1`
    FOREIGN KEY (`TutorExterno_Id` , `Direccion_id`)
    REFERENCES `tap_informatica`.`TutorExterno` (`id` , `Direccion_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Revision` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Revision` (
  `tap_ica_id` INT NOT NULL,
  `detalle` VARCHAR(1024) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `EstadoRevision_id` INT NOT NULL,
  `Evaluador_TAP_id` INT NOT NULL,
  `Evaluador_Usuario_id` INT NOT NULL,
  `Evaluador_ROL_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tap_ica_id`),
  INDEX `fk_Revision_EstadoRevision1_idx` (`EstadoRevision_id` ASC),
  INDEX `fk_Revision_Evaluador1_idx` (`Evaluador_TAP_id` ASC, `Evaluador_Usuario_id` ASC, `Evaluador_ROL_id` ASC),
  CONSTRAINT `fk_Revision_tap_ica1`
    FOREIGN KEY (`tap_ica_id`)
    REFERENCES `tap_informatica`.`tap_ica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Revision_EstadoRevision1`
    FOREIGN KEY (`EstadoRevision_id`)
    REFERENCES `tap_informatica`.`EstadoRevision` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Revision_Evaluador1`
    FOREIGN KEY (`Evaluador_TAP_id` , `Evaluador_Usuario_id` , `Evaluador_ROL_id`)
    REFERENCES `tap_informatica`.`Evaluador` (`TAP_id` , `Usuario_id` , `ROL_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`tap_eus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`tap_eus` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`tap_eus` (
  `TAP_id` INT NOT NULL,
  `Estatus_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`TAP_id`, `Estatus_id`),
  INDEX `fk_tap_eus_Estatus1_idx` (`Estatus_id` ASC),
  CONSTRAINT `fk_tap_eus_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tap_eus_Estatus1`
    FOREIGN KEY (`Estatus_id`)
    REFERENCES `tap_informatica`.`Estatus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`Tesis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`Tesis` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`Tesis` (
  `TAP_id` INT NOT NULL,
  `Usuario_id` INT NOT NULL,
  PRIMARY KEY (`TAP_id`),
  INDEX `fk_Tesis_Usuario1_idx` (`Usuario_id` ASC),
  CONSTRAINT `fk_Tesis_TAP1`
    FOREIGN KEY (`TAP_id`)
    REFERENCES `tap_informatica`.`TAP` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tesis_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `tap_informatica`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `tap_informatica`.`uio_lon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`uio_lon` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`uio_lon` (
  `Usuario_id` INT NOT NULL,
  `LineaInvestigacion_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Usuario_id`, `LineaInvestigacion_id`),
  INDEX `fk_uio_lon_Usuario1_idx` (`Usuario_id` ASC),
  INDEX `fk_uio_lon_LineaInvestigacion1_idx` (`LineaInvestigacion_id` ASC),
  CONSTRAINT `fk_uio_lon_Usuario1`
    FOREIGN KEY (`Usuario_id`)
    REFERENCES `tap_informatica`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uio_lon_LineaInvestigacion1`
    FOREIGN KEY (`LineaInvestigacion_id`)
    REFERENCES `tap_informatica`.`LineaInvestigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_system`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_system` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_system` (
  `idsystem` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `largename` VARCHAR(45) NULL DEFAULT NULL,
  `sessionmaxdurationmins` INT(11) NULL DEFAULT 30,
  `sessionmaxsameipconnections` INT(11) NULL DEFAULT 10,
  `sessionreusesessions` INT(11) NULL DEFAULT 1 COMMENT '1yes 0no',
  `sessionmaxsessionsperday` INT(11) NULL DEFAULT -1,
  `sessionmaxsessionsperuser` INT(11) NULL DEFAULT -1,
  `systemnonewsessions` INT(11) NULL DEFAULT 0 COMMENT '1yes 0no',
  `systemdown` INT(11) NULL DEFAULT 0,
  `registerusingcaptcha` INT(11) NULL DEFAULT 0,
  `registerusingterms` INT(11) NULL DEFAULT 0,
  `terms` BLOB NULL DEFAULT NULL,
  `registerusingactivation` INT(11) NULL DEFAULT 1,
  `defaultroleforregistration` VARCHAR(64) NULL DEFAULT NULL,
  `registerusingtermslabel` VARCHAR(100) NULL DEFAULT NULL,
  `registrationonlogin` INT(11) NULL DEFAULT 1,
  PRIMARY KEY (`idsystem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_session` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_session` (
  `idsession` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `created` BIGINT(30) NULL DEFAULT NULL,
  `expire` BIGINT(30) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT 0,
  `ipaddress` VARCHAR(45) NULL DEFAULT NULL,
  `usagecount` INT(11) NULL DEFAULT 0,
  `lastusage` BIGINT(30) NULL DEFAULT NULL,
  `logoutdate` BIGINT(30) NULL DEFAULT NULL,
  `ipaddressout` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsession`),
  INDEX `crugesession_iduser` (`iduser` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_user` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `regdate` BIGINT(30) NULL DEFAULT NULL,
  `actdate` BIGINT(30) NULL DEFAULT NULL,
  `logondate` BIGINT(30) NULL DEFAULT NULL,
  `username` VARCHAR(64) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(64) NULL DEFAULT NULL COMMENT 'Hashed password',
  `authkey` VARCHAR(100) NULL DEFAULT NULL COMMENT 'llave de autentificacion',
  `state` INT(11) NULL DEFAULT 0,
  `totalsessioncounter` INT(11) NULL DEFAULT 0,
  `currentsessioncounter` INT(11) NULL DEFAULT 0,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_field` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_field` (
  `idfield` INT NOT NULL AUTO_INCREMENT,
  `fieldname` VARCHAR(20) NOT NULL,
  `longname` VARCHAR(50) NULL DEFAULT NULL,
  `position` INT(11) NULL DEFAULT 0,
  `required` INT(11) NULL DEFAULT 0,
  `fieldtype` INT(11) NULL DEFAULT 0,
  `fieldsize` INT(11) NULL DEFAULT 20,
  `maxlength` INT(11) NULL DEFAULT 45,
  `showinreports` INT(11) NULL DEFAULT 0,
  `useregexp` VARCHAR(512) NULL DEFAULT NULL,
  `useregexpmsg` VARCHAR(512) NULL DEFAULT NULL,
  `predetvalue` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfield`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_fieldvalue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_fieldvalue` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_fieldvalue` (
  `idfieldvalue` INT NOT NULL AUTO_INCREMENT,
  `iduser` INT NOT NULL,
  `idfield` INT NOT NULL,
  `value` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idfieldvalue`),
  INDEX `fk_cruge_fieldvalue_cruge_user1` (`iduser` ASC),
  INDEX `fk_cruge_fieldvalue_cruge_field1` (`idfield` ASC),
  CONSTRAINT `fk_cruge_fieldvalue_cruge_user1`
    FOREIGN KEY (`iduser`)
    REFERENCES `tap_informatica`.`cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_fieldvalue_cruge_field1`
    FOREIGN KEY (`idfield`)
    REFERENCES `tap_informatica`.`cruge_field` (`idfield`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_authitem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_authitem` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_authitem` (
  `name` VARCHAR(64) NOT NULL,
  `type` INT(11) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_authassignment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_authassignment` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_authassignment` (
  `userid` INT NOT NULL,
  `bizrule` TEXT NULL DEFAULT NULL,
  `data` TEXT NULL DEFAULT NULL,
  `itemname` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`userid`, `itemname`),
  INDEX `fk_cruge_authassignment_cruge_authitem1` (`itemname` ASC),
  INDEX `fk_cruge_authassignment_user` (`userid` ASC),
  CONSTRAINT `fk_cruge_authassignment_cruge_authitem1`
    FOREIGN KEY (`itemname`)
    REFERENCES `tap_informatica`.`cruge_authitem` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cruge_authassignment_user`
    FOREIGN KEY (`userid`)
    REFERENCES `tap_informatica`.`cruge_user` (`iduser`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tap_informatica`.`cruge_authitemchild`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tap_informatica`.`cruge_authitemchild` ;

CREATE TABLE IF NOT EXISTS `tap_informatica`.`cruge_authitemchild` (
  `parent` VARCHAR(64) NOT NULL,
  `child` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC),
  CONSTRAINT `crugeauthitemchild_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `tap_informatica`.`cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `crugeauthitemchild_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `tap_informatica`.`cruge_authitem` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
